// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfMwWtVS6EigwbKcZXQP0nn88qlM8OZJ0',
    appId: '1:351179856225:web:b7d79bb95002d4f9f80d20',
    messagingSenderId: '351179856225',
    projectId: 'fir-sample-a6115',
    authDomain: 'fir-sample-a6115.firebaseapp.com',
    storageBucket: 'fir-sample-a6115.firebasestorage.app',
    measurementId: 'G-RBHL65259E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuA5vV0e9EfTQrAMCabDfe0dlpqS0JRpw',
    appId: '1:351179856225:android:483d794b9ec5cc49f80d20',
    messagingSenderId: '351179856225',
    projectId: 'fir-sample-a6115',
    storageBucket: 'fir-sample-a6115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpoZBDmQipuwWBc2bNQj_wjUqAtS39nMM',
    appId: '1:351179856225:ios:e9cd4810be735e48f80d20',
    messagingSenderId: '351179856225',
    projectId: 'fir-sample-a6115',
    storageBucket: 'fir-sample-a6115.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSample',
  );
}
